商品管理ページ作成
private-ryomann/rails_ec pull request #4
Opened 2023-08-01 16:26 UTC by private-ryomann

## 課題のリンク

* https://example.com

## やったこと

* このプルリクで何をしたのか？

## 動作確認方法

* 動作確認方法の手順を書いてください

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点、困りごとなど）

2023-08-03 08:49 UTC, ihatov08 requested changes
> basic認証はユーザー名(admin),パスワード(pw)とすること

こちら対応お願いします！

2023-08-03 09:33 UTC, private-ryomann commented
> > basic認証はユーザー名(admin),パスワード(pw)とすること
> 
> こちら対応お願いします！

忘れていました
家に帰ったらすぐに直します！

2023-08-03 11:18 UTC, private-ryomann commented
修正しました！確認の方よろしくお願いします。

2023-08-05 06:13 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-08-05 06:48 UTC, private-ryomann commented
> 確認しました、LGTMです！

忙しい中ありがとうございます！！

2023-08-05 07:21 UTC, merged